status/urls.py
from django.urls import path
from . import views

app_name = 'status'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirm/', views.confirm, name='confirm'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('status.urls')),
]

status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    name = models.CharField(max_length=50,primary_key=True)
    status = models.TextField('status', max_length = 300)
    time = models.DateTimeField(auto_now_add = True, null = True)



    def __str__(self):
        return self.name

status/forms.py
from django import forms
from .models import Status

class StatusForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'required' : True,
        'label' : '',
    }))
    status = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'required' : True,
        'label' : '',
    }))

status/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import Status


# Create your views here.
def index(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if (form.is_valid()):
            new_name = form.cleaned_data['name']
            new_status = form.cleaned_data['status']
            response = {'name':new_name, 'status':new_status}
            return render(request, 'confirm.html', response)
    else:
        form = StatusForm()
    stats = Status.objects.all()
    response = {'stats': stats}
    return render(request, 'index.html', response)


def confirm(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if (form.is_valid()):
            new_user = Status()
            new_user.name = form.cleaned_data['name']
            new_user.status = form.cleaned_data['status']
            new_user.save()
            return redirect('/')
    else:
        form = StatusForm()
    return render(request, 'confirm.html')

status/templates/confirm.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/CSS">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Confirmation</title>
</head>
<body>
    <br><br><br><br><br><br>
    <h1>Are you sure to submit this form?</h1>
    <form action="{% url 'status:confirm' %}" method="POST">
        {% csrf_token %}
        <div style="margin-left: 10px; margin-right: 10px;">
            <div class="form-row">
                <div class="col-sm-1"></div>
                <div class="form-group col-sm-10">
                    <h2>Name:</h2>
                    <input type="text" class="form-control" id="status" name="name" maxlength="50" readonly value="{{ name }}">
                    <br>
                    <h2>Status:</h2>
                    <input type="text" class="form-control" id="status" name="status" maxlength="50" readonly value="{{ status }}">
                </div>
            </div>
        </div>
        <br>
        <div class="container">
            <div class="col-sm-5" style="padding-left: 50%;">
                <input type="submit" name="confirm" value="Submit">
            </div>
            <div class="col-sm-5" style="padding-left: 50%;">
                <a href="{% url 'status:index' %}" name="cancel">Cancel</a>
            </div>
        </div>
    </form> 
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

status/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/CSS">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>How are you?</title>
</head>
<body>
    <br><br><br><br><br><br>
   <h1>Hello, how are you?</h1>
   <br>
   <form method="POST">
    {% csrf_token %}
    <div class="row">
        <input type="text" class="form" id="status" name="name" placeholder="What's your name?" required>
    </div>
    <br>
    <div class="row">
        <input type="text" class="form" id="status" name="status" placeholder="How are you?" required>
    </div>
    <br>
    <div class="col-md-12">
        <div class="text-center">
            <button type="submit" class="btn" style="background-color: #90303d; color: aliceblue; border-radius: 50px;" name="submit" >Submit</button> 
        </div>
    </div>
    
   </form>
   <br>
   <div>
    <div class="col-md-12">
        <div class="text-center">
            <p id="status">Status Board</p>
            <button onclick="change()" style="background-color: #90303d; color: aliceblue; border-radius: 50px;" id="changeColor" class="btn">Change Color</button>
            <p> 
                {% for stats in stats %}
                <div class="statusbox">
                    <div class="row">
                        <div class="col-sm">
                            <p class="statuss" style="color: white;"> {{ stats.name }}</p>
                        </div>
                        <div class="col-sm">
                            <p class="statuss" style="color: white;"> {{ stats.status }}</p>
                        </div>
                        <div class="col-sm">
                            <p class="statuss" style="color: white;">{{ stats.time }}</p>
                        </div> 
                    </div>  
                </div>
                <br> 
                {% endfor %}
            </p>               
        </div>
    </div>
</div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
<script>
    function change() {
      var status_table = document.getElementsByClassName("statuss");
      var i;
      for(i = 0; i < status_table.length; i++) {
        status_table[i].style.color = "rgba(126, 237, 241, 1)";
      }        
    }
  </script>

</html>